apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  labels:
    accelerator.apps.tanzu.vmware.com/category: platform
  name: managed-platform-accelerators
spec:
  serviceAccountName: accelerator-managed-resources

  fetch:
  - git:
      url: https://github.com/sample-accelerators/managed-platform
      ref: origin/main
      subPath: resources

  template:
  - ytt: {}
  deploy: 
  - kapp: {}
